# -*- coding: utf-8 -*-
"""Import.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VPZIsbBixgtpvJeS1CvtL7s3TJAD0mKp
"""

import hashlib
import json
import time
import random
import base64
from typing import Dict, List, Tuple, Optional, Union
from dataclasses import dataclass, asdict
from datetime import datetime, timedelta
from enum import Enum
import secrets
import string

# Cryptographic imports
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa, padding, ed25519
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
import math